[build-system]
build-backend = "maturin"
requires = ["maturin>=1.0,<2.0"]

[project]
dependencies = [
  "marimo>=0.23.3",
  "matplotlib>=3.10.8",
  "maturin>=1.13.1",
  "pandas>=3.0.2",
  "plotly>=6.7.0",
  "scipy>=1.17.1",
  "tabulate>=0.10.0",
  "zernike>=0.0.33",
]
description = "Add your description here"
name = "lightbender"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[tool.maturin]
manifest-path = "raytracer/Cargo.toml"
module-name = "_raytracer_rs"

[dependency-groups]
dev = [
  "watchfiles>=1.1.1",
]
[tool.marimo.runtime]
output_max_bytes = 10_000_000
